name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: ./build.yml

    - name: Upload Release Asset
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
