name: release

on:
    release:
      types:
        - created
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and test
      run: |
        ./gradlew clean assembleDebug
        ./gradlew testDebug

    - name: Upload Release Asset
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
